[package]
name = "arb-bot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures-util = "0.3.24"
tokio = { version = "1.21.1", features = ["full"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws"] }